'''
Created on 03-Jun-2018

@author: srinivasan
'''
from scrapy import Item, Field
from scrapy.loader.processors import TakeFirst, Join, MapCompose


class MarylandItems(Item):
    permit_lic_no = Field()
    company_name = Field()
    location_address_string = Field()
    mixed_name = Field()
    mixed_subtype = Field()
    agent_address_string = Field()
    mail_address_string = Field()
    permit_lic_status = Field()
    good_standing = Field()
    company_type = Field()
    business_code = Field()
    creation_date = Field()
    hq_indicator = Field()
    public_private_indicator = Field()
    close_status = Field()
    permit_lic_eff_date = Field()
    permit_lic_exp_date = Field()
    date_time_filed = Field()
    inactive_date = Field()
    source_name = Field()
    ingestion_timestamp = Field()
    url = Field()
    permit_type = Field()


class NyAlbanyStateItems(Item):
    permit_lic_no = Field()
    permit_lic_eff_date = Field()
    application_number = Field()        
    location_address_string = Field()
    person_name = Field()
    person_subtype = Field()
    contractor_name = Field()
    permit_lic_value = Field()    
    permit_lic_fee = Field()
    permit_lic_desc = Field()
    longitude = Field()
    latitude = Field()
    permit_type = Field()
    url = Field()
    sourceName = Field()
    ingestion_timestamp = Field()


class NyauthorityItem(Item):    
    company_name = Field()
    mixed_name = Field()
    mixed_subtype = Field()
    dba_name = Field()
    zone = Field()
    county = Field()
    permity_subtype = Field()
    permit_lic_exp_date = Field()
    permit_licence_status = Field()
    permit_lic_no = Field()
    credit_group = Field()
    permit_lic_eff_date = Field()
    permit_applied_date = Field()
    permit_type = Field()
    source_name = Field()
    url = Field()
    ingestion_timestamp = Field()
    location_address_string = Field()
    licence_class = Field()
    licence_type_code = Field()


class NyvehicleinspectionsItem(Item):
    permit_lic_no = Field()
    company_name = Field()
    location_address_string = Field()
    county = Field()
    mixed_name = Field()
    mixed_subtype = Field()
    ops_desc = Field()
    permit_lic_eff_date = Field()
    last_renewal_date = Field()
    permit_lic_exp_date = Field()
    permit_type = Field()
    url = Field()
    sourceName = Field()
    ingestion_timestamp = Field()


class NystatelicensesItem(Item):
    permit_lic_no = Field()
    person_name = Field()
    company_name = Field()
    location_address_string = Field()
    county = Field()
    permit_subtype = Field()
    permit_lic_exp_date = Field()
    training = Field()
    date_completed = Field()
    permit_type = Field()
    url = Field()
    sourceName = Field()
    ingestion_timestamp = Field()

    
class TXLewisvilleFoodInspectionItem(Item):
    company_name = Field()
    inspection_date = Field()
    inspection_score = Field()    
    location_address_string = Field()
    inspection_type = Field()
    sourceName = Field()
    url = Field()
    ingestion_timestamp = Field()


class CO_Larimer_FoodItem(Item):
    company_name = Field()
    mixed_name = Field(output_processor=TakeFirst())   
    mixed_subtype = Field() 
    location_address_string = Field()
    est_site = Field(output_processor=TakeFirst())
    license_posted = Field()
    inspection_date = Field() 
    follow_up_required = Field()    
    seating_capacity = Field() 
    inspection_subtype = Field() 
    inspection_score = Field()   
    violation_rule_id = Field()
    violation_subtype = Field()
    violation_rule = Field()
    violation_points = Field()
    violation_description = Field()
    inspector_comments = Field(output_processor=Join())
    inspection_type = Field(output_processor=MapCompose(lambda v: v.replace(',', "")))
    violation_type = Field()
    violation_date = Field()
    abate_date = Field()
    abate_status = Field()
    sourceName = Field()
    url = Field()
    ingestion_timestamp = Field()


class CO_El_Paso_Food_InspectionItem(Item):
    company_name = Field()
    location_address_string = Field()
    inspection_date = Field()
    inspection_subtype = Field()
    inspection_score = Field()
    violation_rule_id = Field()
    violation_rule = Field(
        input_processor=MapCompose(lambda x: ''.join(c for c in x if  c not in '*?:!/;'))
        )
    violation_description = Field()
    inspection_type = Field()
    violation_date = Field()
    violation_type = Field()
    sourceName = Field()
    url = Field()
    ingestion_timestamp = Field()


class PA_NorthamptonItem(Item):
    activity = Field()
    permit_lic_status = Field()
    permit_lic_eff_date = Field()
    permit_subtype = Field()
    mixed_name = Field()
    mixed_subtype = Field()
    permit_lic_no = Field()
    permit_lic_desc = Field()
    location_address_string = Field()
    permit_type = Field()
    url = Field()
    sourceName = Field()
    ingestion_timestamp = Field()


class PABusinessLicensesItem(Item):
    company_name = Field()
    name_type = Field()
    location_address_string = Field()
    permit_lic_no = Field()
    company_type = Field()
    status = Field()
    permit_lic_status = Field()
    citizenship = Field()
    creation_date = Field()
    permit_lic_eff_date = Field()
    state_of_inc = Field()
    person_name = Field()
    person_subtype = Field()
    person_address_string = Field()
    permit_type = Field()
    url = Field()
    sourceName = Field()
    ingestion_timestamp = Field()


class NyCompaniesDolDebarredlicensesItem(Item):
    mixed_name = Field()
    dba_name = Field()
    permit_lic_status = Field()
    permit_lic_exp_date = Field()
    agency = Field()
    fiscal_officer = Field()
    company_ein = Field()
    location_address_string = Field()
    issuance_date = Field()
    end_date = Field()
    permit_type = Field()
    sourceName = Field()
    url = Field()
    ingestion_timestamp = Field()
